# Formula generated by packaging/homebrew/update-formula.sh
# Do not edit manually -- re-run the script after each release.
class ForgejoCliPlus < Formula
  desc "CLI tool for Forgejo -- like gh for GitHub"
  homepage "https://codeberg.org/stalecontext/forgejo-cli-plus"
  version "VERSION"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_intel do
      url "https://codeberg.org/stalecontext/forgejo-cli-plus/releases/download/vVERSION/forgejo-cli-plus-macos-x86_64.tar.gz"
      sha256 "SHA256_MACOS_X86_64"
    end
    on_arm do
      url "https://codeberg.org/stalecontext/forgejo-cli-plus/releases/download/vVERSION/forgejo-cli-plus-macos-aarch64.tar.gz"
      sha256 "SHA256_MACOS_AARCH64"
    end
  end

  on_linux do
    on_intel do
      url "https://codeberg.org/stalecontext/forgejo-cli-plus/releases/download/vVERSION/forgejo-cli-plus-linux-x86_64.tar.gz"
      sha256 "SHA256_LINUX_X86_64"
    end
  end

  def install
    bin.install "fj"
  end

  test do
    assert_match "fj", shell_output("#{bin}/fj version")
  end
end
